---
- name: add nomodeset
  replace: 
    replace: GRUB_CMDLINE_LINUX_DEFAULT="nomodeset consoleblank=0"
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT.*$"
    dest: "/etc/default/grub"
  sudo: yes
  sudo_user: root
  notify: 
    - update grub

- name: add chrome repo key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: add apt repos
  apt_repository: "repo='{{item}}' update_cache=yes"
  with_items:
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted
    - deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
    - deb http://us.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
    - deb http://security.ubuntu.com/ubuntu trusty-security main restricted

- name: "chrome dependencies"
  apt: "name={{ item.name }} state={{ item.state | default('present') }} purge={{ item.purge | default('no') }} install_recommends={{ item.install_recommends | default('yes') }} update_cache=yes cache_valid_time=600"
  with_items:
    - {name: ubuntu-desktop, install_recommends: no}
    - {name: google-chrome-stable}
    - {name: lightdm-gtk-greeter}
    - {name: arandr}
    - {name: unclutter}
    - {name: matchbox-window-manager}
    - {name: nvidia-331}
    - {name: xserver-xorg-video-nouveau, state: absent, purge: yes}
    - {name: privoxy}
  sudo: yes
  sudo_user: root

- name: hold chrome version
  command: /usr/bin/apt-mark hold google-chrome-stable
  sudo: yes
  sudo_user: root

- name: copy kiosk script
  copy:
    src: chromeKiosk.sh
    dest: "/usr/share/xsessions/chromeKiosk.sh"
    mode: 0755
  sudo: yes
  sudo_user: root

- name: copy privoxy config
  copy:
    src: privoxy-config
    dest: "/etc/privoxy/config"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: copy privoxy trustfile
  copy:
    src: trust
    dest: "/etc/privoxy/trust"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: copy privoxy templates
  copy:
    src: untrusted
    dest: "/etc/privoxy/templates/untrusted"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: copy desktop config
  copy:
    src: kiosk.desktop
    dest: "/usr/share/xsessions/kiosk.desktop"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: copy lightdm config
  template:
    src: lightdm.conf.j2
    dest: "/etc/lightdm/lightdm.conf"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: create chrome policy dir
  file:
    path: /etc/opt/chrome/policies/managed
    mode: u=rwx,g=rx,o=rx
    state: directory
  sudo: yes
  sudo_user: root

- name: copy chrome policy
  copy:
    src: videowall_policy.json
    dest: "/etc/opt/chrome/policies/managed/videowall_policy.json"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: copy display setup script
  copy:
    src: displaySetup.sh
    dest: "/usr/share/xsessions/displaySetup.sh" # TODO: better place to put this?
    mode: 0755
  sudo: yes
  sudo_user: root

# - name: download nvidia driver
#   get_url:
#     dest: /tmp
#     url: http://us.download.nvidia.com/XFree86/Linux-x86_64/352.41/NVIDIA-Linux-x86_64-352.41.run
#     sha256sum: 0eb60d0543a0e7c5c3cfec13702005ffec6e2b8c7f22c631f324736ba2a1a832
#     mode: 0755

# - name: install nvidia driver
#   command: /tmp/NVIDIA-Linux-x86_64-352.41.run --accept-license --no-questions --ui=none
#   sudo: yes
#   sudo_user: root
#   args: 
#     creates: /usr/lib/libnvidia-glcore.so.352.41

- name: set up nvidia driver
  command: /usr/bin/nvidia-xconfig
  sudo: yes
  sudo_user: root
  args: 
    creates: /etc/X11/xorg.conf

- name: copy display power script
  copy:
    src: displays_on.sh
    dest: "/usr/local/bin/displays_on.sh"
    group: dialout
    mode: 0755
  sudo: yes
  sudo_user: root

- name: copy display power script
  copy:
    src: displays_off.sh
    dest: "/usr/local/bin/displays_off.sh"
    group: dialout
    mode: 0755
  sudo: yes
  sudo_user: root

