---
- name: install desktop
  apt: name=ubuntu-desktop install_recommends=no

- name: add chrome repo key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: add chrome apt repo
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' update_cache=yes

- name: install chrome
  apt: name=google-chrome-stable update_cache=yes

- name: install lightdm-gtk-greeter
  apt: name=lightdm-gtk-greeter

- name: install matchbox-window-manager
  apt: name=matchbox-window-manager

- name: copy kiosk script
  copy:
    src: chromeKiosk.sh
    dest: "/usr/share/xsessions/chromeKiosk.sh"
    mode: 0755
  sudo: yes
  sudo_user: root

- name: copy desktop config
  copy:
    src: kiosk.desktop
    dest: "/usr/share/xsessions/kiosk.desktop"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: copy lightdm config
  template:
    src: lightdm.conf.j2
    dest: "/etc/lightdm/lightdm.conf"
    mode: 0644
  sudo: yes
  sudo_user: root

# - name: download nvidia driver
#   get_url:
#     dest: /tmp
#     url: http://us.download.nvidia.com/XFree86/Linux-x86_64/340.65/NVIDIA-Linux-x86_64-340.65.run
#     sha256sum: cd3948db5c1e2468c50140efb4bb50f1a4c84c923db8ec756bd56ff35df9ff04
#     mode: 0644

# - name: install nvidia driver
#   command: /tmp/NVIDIA-Linux-x86_64-340.65.run --accept-license --no-questions --ui=none --run-nvidia-xconfig
#   sudo: yes
#   sudo_user: root
