---
- name: add nomodeset
  replace: 
    replace: GRUB_CMDLINE_LINUX_DEFAULT="nomodeset consoleblank=0"
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT.*$"
    dest: "/etc/default/grub"
  sudo: yes
  sudo_user: root
  notify: 
    - update grub

- name: add chrome repo key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: add chrome apt repo
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' update_cache=yes

- name: "chrome dependencies"
  apt: "name={{ item.name }} state={{ item.state | default('present') }} purge={{ item.purge | default('no') }} install_recommends={{ item.install_recommends | default('yes') }} update_cache=yes cache_valid_time=600"
  with_items:
    - {name: ubuntu-desktop, install_recommends: no}
    - {name: google-chrome-stable}
    - {name: lightdm-gtk-greeter}
    - {name: arandr}
    - {name: unclutter}
    - {name: matchbox-window-manager}
    - {name: nvidia-331}
    - {name: xserver-xorg-video-nouveau, state: absent, purge: yes}
  sudo: yes
  sudo_user: root


- name: copy kiosk script
  copy:
    src: chromeKiosk.sh
    dest: "/usr/share/xsessions/chromeKiosk.sh"
    mode: 0755
  sudo: yes
  sudo_user: root

- name: copy desktop config
  copy:
    src: kiosk.desktop
    dest: "/usr/share/xsessions/kiosk.desktop"
    mode: 0644
  sudo: yes
  sudo_user: root

- name: copy lightdm config
  template:
    src: lightdm.conf.j2
    dest: "/etc/lightdm/lightdm.conf"
    mode: 0644
  sudo: yes
  sudo_user: root

# - name: download nvidia driver
#   get_url:
#     dest: /tmp
#     url: http://us.download.nvidia.com/XFree86/Linux-x86_64/340.65/NVIDIA-Linux-x86_64-340.65.run
#     sha256sum: cd3948db5c1e2468c50140efb4bb50f1a4c84c923db8ec756bd56ff35df9ff04
#     mode: 0755

# - name: install nvidia driver
#   command: /tmp/NVIDIA-Linux-x86_64-340.65.run --accept-license --no-questions --ui=none
#   sudo: yes
#   sudo_user: root
#   args: 
#     creates: /usr/lib/libnvidia-glcore.so.340.65

- name: set up nvidia driver
  command: /usr/bin/nvidia-xconfig
  sudo: yes
  sudo_user: root
  args: 
    creates: /etc/X11/xorg.conf
