---
- name: Copy deploy key file
  copy: src="../../../id_rsa"
        dest=/home/{{ panesfe_user }}/.ssh/id_rsa_github
        mode=0600
        owner={{ panesfe_user }}
        group={{ panesfe_user }}

- name: deploy app
  git: dest={{ panesfe_checkout_dir }}
       repo=ssh://git@github.com/aocole/panesfe.git
       depth=1
       ssh_opts="-i /home/{{ panesfe_user }}/.ssh/id_rsa_github"
       accept_hostkey=yes
  notify:
    - restart unicorn

- name: install bundler
  command: bash -lc "gem install bundler; rbenv rehash"
  args:
    chdir: "{{ panesfe_checkout_dir }}"
  become_user: "{{ panesfe_user }}"

- name: install {{ item }}
  apt: name={{ item }}
  become_user: root
  with_items:
    - libpq-dev
    - imagemagick
    - libav-tools

- name: bundle install
  command: bash -lc "bundle install --without development test"
  args:
    chdir: "{{ panesfe_checkout_dir }}"
  become_user: "{{ panesfe_user }}"

- name: create tmp dir
  command: bash -lc "mkdir -p {{ panesfe_checkout_dir }}/tmp/pids; mkdir -p {{ panesfe_checkout_dir }}/tmp/sockets"

- include_vars: ../../../secrets.yml
  no_log: True

- name: template app secrets
  template: 
    dest: "{{ panesfe_checkout_dir }}/config/secrets.yml"
    mode: u=rw,g=r
    src: ../templates/secrets.yml.j2

- name: mount upload drive
  mount:
    fstype: ext4
    name: "{{ panesfe_upload_drive_mount_point }}"
    src: "{{ panesfe_upload_drive_dev }}"
    state: mounted
  become_user: root
  when: panesfe_upload_root_dir is defined

- name: set permissions on upload dir
  file:
    mode: u=rwx,g=rx,o=rx
    owner: panesfe
    path: "{{ panesfe_upload_root_dir }}"
    state: directory
  become_user: root
  when: panesfe_upload_root_dir is defined

- name: migrate db
  command: bash -lc "RAILS_ENV=production bundle exec rake db:migrate"
  args:
    chdir: "{{ panesfe_checkout_dir }}"

- name: seed db
  command: bash -lc "RAILS_ENV=production bundle exec rake db:seed"
  args:
    chdir: "{{ panesfe_checkout_dir }}"

- name: precompile assets
  command: bash -lc "RAILS_ENV=production bundle exec rake assets:precompile"
  args:
    chdir: "{{ panesfe_checkout_dir }}"

- name: template nginx config
  template: 
    dest: /etc/nginx/sites-available/panesfe
    group: root
    owner: root
    mode: u=rw,g=r,o=r
    src: ../templates/panesfe.j2
  notify:
    - restart nginx
  become_user: root

- name: Nginx | Disable the default site
  file:
    path: "{{nginx_dir}}/sites-enabled/default"
    state: absent
  notify:
    - restart nginx
  become_user: root

- name: Nginx | Enable panesfe site
  file:
    path: "{{nginx_dir}}/sites-enabled/panesfe"
    src: "{{nginx_dir}}/sites-available/panesfe"
    state: link
  notify:
    - restart nginx
  become_user: root
