---
- name: Copy deploy key file
  copy: src="../../../id_rsa"
        dest=/home/{{ panesfe.user }}/.ssh/id_rsa_github
        mode=0600
        owner={{ panesfe.user }}
        group={{ panesfe.user }}

- name: deploy app
  git: dest={{ panesfe.checkout_dir }}
       repo=ssh://git@github.com/aocole/panesfe.git
       depth=1
       ssh_opts="-i /home/{{ panesfe.user }}/.ssh/id_rsa_github"
       accept_hostkey=yes
  notify:
    - restart unicorn

- name: install bundler
  command: bash -lc "gem install bundler; rbenv rehash"
  args:
    chdir: "{{ panesfe.checkout_dir }}"

- name: install {{ item }}
  apt: name={{ item }}
  sudo: yes
  sudo_user: root
  with_items:
    - libpq-dev
    - imagemagick
    - libav-tools

- name: bundle install
  command: bash -lc "bundle install --without development test"
  args:
    chdir: "{{ panesfe.checkout_dir }}"

- name: create tmp dir
  command: bash -lc "mkdir -p {{ panesfe.checkout_dir }}/tmp/pids; mkdir -p {{ panesfe.checkout_dir }}/tmp/sockets"

- include_vars: ../../../secrets.yml
  no_log: True

- name: template app secrets
  template: 
    dest: "{{ panesfe.checkout_dir }}/config/secrets.yml"
    mode: u=rw,g=r
    src: ../templates/secrets.yml.j2

- name: migrate db
  command: bash -lc "RAILS_ENV=production bundle exec rake db:migrate"
  args:
    chdir: "{{ panesfe.checkout_dir }}"

- name: seed db
  command: bash -lc "RAILS_ENV=production bundle exec rake db:seed"
  args:
    chdir: "{{ panesfe.checkout_dir }}"

- name: precompile assets
  command: bash -lc "RAILS_ENV=production bundle exec rake assets:precompile"
  args:
    chdir: "{{ panesfe.checkout_dir }}"

- name: template nginx config
  template: 
    dest: /etc/nginx/sites-available/panesfe
    group: root
    owner: root
    mode: u=rw,g=r,o=r
    src: ../templates/panesfe.j2
  notify:
    - restart nginx
  sudo: yes
  sudo_user: root

- name: Nginx | Disable the default site
  file:
    path: "{{nginx_dir}}/sites-enabled/default"
    state: absent
  notify:
    - restart nginx
  sudo: yes
  sudo_user: root

- name: Nginx | Enable panesfe site
  file:
    path: "{{nginx_dir}}/sites-enabled/panesfe"
    src: "{{nginx_dir}}/sites-available/panesfe"
    state: link
  notify:
    - restart nginx
  sudo: yes
  sudo_user: root
