---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  vars:
    panesfe:
      checkout_dir: "/home/panes/panesfe"
      user: panes
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.1.5
    rbenv_users:
      - { name: "{{ panesfe.user }}", home: "/home/{{ panesfe.user }}/", comment: "Deploy user" }
    rails_apps:
      - name: panesfe
        ruby_version: 2.1.5
        root: "{{ panesfe.checkout_dir }}"
    nginx_install_method: package
    rbenv_root: "{{ rbenv_users[0].home }}/.rbenv"
    rbenv_exe: "{{ rbenv_root }}/bin/rbenv"

  roles:
    - { role: app-user,              sudo: yes, sudo_user: root }
    - { role: ANXS.monit,            sudo: yes, sudo_user: root }
    - { role: ANXS.postgresql,       sudo: yes, sudo_user: root }
    - { role: zzet.rbenv,            sudo: yes, sudo_user: root }
    - { role: ANXS.nginx,            sudo: yes, sudo_user: root }
    - { role: ansible-unicorn-rbenv, sudo: yes, sudo_user: root }
    - { role: chrome,                sudo: yes, sudo_user: root }
    - { role: deploy-app,            sudo: yes, sudo_user: "{{ panesfe.user }}" }
