---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  vars:
    videowall_user: videowall
    panesfe_checkout_dir: "/home/panesfe/panesfe"
    panesfe_user: panesfe
    panesd_user: panesd
    panesd_github_checkout: github.com/aocole/panesd
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.1.5
    rbenv_users:
      - { name: "{{ panesfe_user }}", home: "/home/{{ panesfe_user }}/", comment: "Deploy user" }
    rails_apps:
      - name: panesfe
        ruby_version: 2.1.5
        root: "{{ panesfe_checkout_dir }}"
    nginx_install_method: package
    rbenv_root: "{{ rbenv_users[0].home }}/.rbenv"
    rbenv_exe: "{{ rbenv_root }}/bin/rbenv"
    # List of databases to be created (optional)
    postgresql_databases:
      - name: panesfe
        # hstore: yes         # flag to install the hstore extension on this database (yes/no)
        # uuid_ossp: yes      # flag to install the uuid-ossp extension on this database (yes/no)

    # List of users to be created (optional)
    postgresql_users:
      - name: panesfe
        pass: panesfe # TODO: generate
        encrypted: no       # denotes if the password is already encrypted.
    monit_protection: true

  roles:
    - { role: apt-upgrade,           sudo: yes, sudo_user: root, tags: ['apt', 'upgrade'] }
    - { role: app-user,              sudo: yes, sudo_user: root, tags: ['users'] }
    - { role: ANXS.monit,            sudo: yes, sudo_user: root }
    - { role: ANXS.postgresql,       sudo: yes, sudo_user: root }
    - { role: zzet.rbenv,            sudo: yes, sudo_user: root, tags: ['rbenv'] }
    - { role: ANXS.nginx,            sudo: yes, sudo_user: root }
    - { role: ansible-unicorn-rbenv, sudo: yes, sudo_user: root, tags: ['unicorn'] }
    - { role: cec-control,           sudo: yes, sudo_user: root, tags: ['cec'] }
    - { role: chrome,                sudo: yes, sudo_user: root, tags: ['chrome'] }
    - { role: videowall-config,      sudo: yes, sudo_user: root, tags: ['panesd', 'panesfe', 'deploy'] }
    - { role: deploy-app,            become_user: "{{ panesfe_user }}",   tags: ['panesfe', 'deploy'] }
    - { role: deploy-panesd,         sudo: yes, sudo_user: "{{ panesd_user }}",    tags: ['panesd', 'deploy'] }
