---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  vars:
    videowall:
      user: videowall
    panesfe:
      checkout_dir: "/home/panesfe/panesfe"
      user: panesfe
    panesd:
      user: panesd
      github_checkout: github.com/aocole/panesd
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.1.5
    rbenv_users:
      - { name: "{{ panesfe.user }}", home: "/home/{{ panesfe.user }}/", comment: "Deploy user" }
    rails_apps:
      - name: panesfe
        ruby_version: 2.1.5
        root: "{{ panesfe.checkout_dir }}"
    nginx_install_method: package
    rbenv_root: "{{ rbenv_users[0].home }}/.rbenv"
    rbenv_exe: "{{ rbenv_root }}/bin/rbenv"
    # List of databases to be created (optional)
    postgresql_databases:
      - name: panesfe
        # hstore: yes         # flag to install the hstore extension on this database (yes/no)
        # uuid_ossp: yes      # flag to install the uuid-ossp extension on this database (yes/no)

    # List of users to be created (optional)
    postgresql_users:
      - name: panesfe
        pass: panesfe # TODO: generate
        encrypted: no       # denotes if the password is already encrypted.

  roles:
    - { role: app-user,              sudo: yes, sudo_user: root, tags: ['users'] }
    - { role: ANXS.monit,            sudo: yes, sudo_user: root }
    - { role: ANXS.postgresql,       sudo: yes, sudo_user: root }
    - { role: zzet.rbenv,            sudo: yes, sudo_user: root }
    - { role: ANXS.nginx,            sudo: yes, sudo_user: root }
    - { role: ansible-unicorn-rbenv, sudo: yes, sudo_user: root, tags: ['unicorn'] }
    - { role: cec-control,           sudo: yes, sudo_user: root, tags: ['cec'] }
    - { role: chrome,                sudo: yes, sudo_user: root, tags: ['chrome'] }
    - { role: deploy-app,            sudo: yes, sudo_user: "{{ panesfe.user }}", tags: ['deploy'] }
    - { role: deploy-panesd,         sudo: yes, sudo_user: "{{ panesd.user }}", tags: ['panesd'] }
