---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  sudo: yes

  vars:
    rbenv:
      env: system
      version: v0.4.0
      ruby_version: 2.1.5

  roles:
    - ANXS.monit
    - ANXS.postgresql
    - zzet.rbenv
    - ANXS.nginx

  tasks:
    - name: add chrome repo key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
    - name: add chrome apt repo
      apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' update_cache=yes
    - name: install chrome
      apt: name=google-chrome-stable update_cache=yes
