---
# tasks file for app-user
- name: create app user
  user: name={{panesfe.user}}
  args:
    shell: /bin/bash
- name: create videowall user
  user: name={{videowall.user}}
  args:
    shell: /bin/bash
