---
# tasks file for app-user
- name: create app user
  user: name={{panesfe.user}}
  args:
    shell: /bin/bash
- name: create videowall user
  user: name={{videowall.user}}
  args:
    shell: /bin/bash
    groups: dialout # necessary so videowall user can access USB CEC devices
- name: create panesd user
  user: name={{panesd.user}}
  args:
    shell: /bin/bash
