---
# tasks file for app-user
- name: create app user
  user: name={{panesfe.user}}
  args:
    shell: /bin/bash
- name: create videowall user
  user: name={{videowall.user}}
  args:
    shell: /bin/bash
    groups: dialout # necessary so videowall user can access USB CEC devices
- name: create panesd user
  user: name={{panesd.user}}
  args:
    shell: /bin/bash

- name: add github to known hosts
  lineinfile: 
    line: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    dest: /etc/ssh/known_hosts
    create: yes
    regexp: ^github\\.com .*$
