---
- name: download Go
  get_url:
    url: https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz
    dest: /tmp/go-dist.tgz
    sha256sum: 68170d5d48fc317155e69d2b55e4c09878433462ddb77d7900db6590ce2bef49

- name: install Go
  command: "tar -C /usr/local -xzf /tmp/go-dist.tgz"
  args: 
    creates: /usr/local/go/bin/go
  sudo: true
  sudo_user: root

- name: add Go to PATH
  lineinfile: 
    line: "export PATH=$PATH:/usr/local/go/bin"
    regexp: "^export PATH=$PATH:/usr/local/go/bin$"
    dest: "/etc/profile"
  sudo: true
  sudo_user: root

- name: set GOPATH
  lineinfile: 
    line: "export GOPATH=$HOME"
    regexp: "^export GOPATH=\\$HOME$"
    dest: "/home/{{ panesd_user }}/.bashrc"
    insertbefore: "^# If not running interactively, don't do anything$"

- name: Create .ssh dir
  file: path=/home/{{ panesd_user }}/.ssh
        state=directory

- name: Copy deploy key file
  copy: src="../../../id_rsa"
        dest=/home/{{ panesd_user }}/.ssh/id_rsa_github
        mode=0600
        owner={{ panesd_user }}
        group={{ panesd_user }}

- name: deploy app
  git: dest=/home/{{ panesd_user }}/src/{{ panesd_github_checkout }}
       repo=ssh://git@{{ panesd_github_checkout }}.git
       key_file=/home/{{ panesd_user }}/.ssh/id_rsa_github
       accept_hostkey=yes
       depth=1

- name: go get dependencies
  command: bash -lc "go get"
  args:
    chdir: "/home/{{ panesd_user }}/src/{{ panesd_github_checkout }}"

- name: go build/install
  command: bash -lc "go install"
  args:
    chdir: "/home/{{ panesd_user }}/src/{{ panesd_github_checkout }}"

- name: Install panesd init script
  template: src=etc/init.d/panesd dest=/etc/init.d/panesd owner=root group=root mode=0755
  sudo: true
  sudo_user: root

- name: Enable panesd service
  service: name=panesd enabled=yes
  sudo: true
  sudo_user: root

- include: cec_control.yml

- include: monit.yml
  when: monit_protection is defined and monit_protection == true
